config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'welcome/about'
  get 'welcome/blog'
  resources :projects, only: [:index, :show]
  resources :posts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ApplicationHelper
  after_create :body_path

  private
  def body_path
    self.body = "posts/post_folder/#{readableToU(self.title)}"
    self.save
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include ApplicationHelper
  has_many :images, dependent: :destroy

  after_create :body_path
  default_scope { order('id DESC')}

  def multi_img?
    self.images.length > 1 ? true : false
  end

  private
  def body_path
    self.body = "projects/project_folder/#{readableToU(self.name)}"
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
include ApplicationHelper

  def index
    @projects = Project.all
    @pro_projects = Project.where(professional: true)
    @personal_projects = Project.where(personal: true)
    @edu_projects = Project.where(educational: true)
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  after_action :set_session

  def blog
    @posts = Post.paginate(page: params[:page], per_page: 5).order('id DESC')
    @visited = session[:visited]
  end

  private
  def set_session
    session[:visited] = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def uToReadable(string)
    string.downcase.gsub(/_/, " ")
  end
  def readableToU(string)
    string.downcase.gsub(/\s/, "_")
  end
  def find_project_id_by_img(name)
    project = Project.find_by_main_img(name)
    project.id
  end
end

app/views/layouts/_portFooter.html.erb
<div class='footerBar text-center'>
  <div class="copy_right">Stephen Wentling © <%= Time.current.year %></div>
</div>

app/views/layouts/_portHeader.html.erb
<section class="headerBar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-xs-12">
        <%= link_to(image_tag("http:\/\/0.gravatar.com\/avatar\/95add28d8792fa4af0f190344db456ac", class: "pull-left image-responsive img-circle face"), root_path) %>
        <h1 class="bannerMessage hidden-sm hidden-xs"><%= link_to('swentling.com', root_path) %></h1>
        <h2 class="bannerMessage hidden-lg hidden-md"><%= link_to('swentling.com', root_path) %></h2>
        <small><%= link_to('Blog', welcome_blog_path, class: "header-link") %></small>
        <small><%= link_to('Projects', projects_path, class: "header-link") %></small>
        <small><%= link_to('About', welcome_about_path, class: "header-link") %></small>
        <small><%= link_to('Resume', asset_path("resume_web.pdf") , class: "header-link") %></small>
      </div>
      <div class="icon-row col-md-2 col-xs-12 text-center">
        <div class="col-xs-3">
          <%= link_to("", "https://github.com/swentling87", class: "fa fa-github") %>
        </div>
        <div class="col-xs-3">
            <%= link_to("", "https://www.linkedin.com/in/stephen-wentling-b3900329?trk=hp-identity-photo", class: "fa fa-linkedin-square") %>
        </div>
        <div class="col-xs-3">
          <%= link_to("", "http://stackoverflow.com/users/5992270/stephen-w", class: "fa fa-stack-overflow") %>
        </div>
        <div class="col-xs-3">
          <%= mail_to("stephen@swentling.com", "", class: "fa fa-envelope") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Sansita" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/e21bfe2a3d.js"></script>
    <script src="https://cdn.rawgit.com/vast-engineering/jquery-popup-overlay/1.7.13/jquery.popupoverlay.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeit/4.3.0/typeit.min.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-99239085-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <script>
      var visited = "<%= @visited %>"
    </script>
    <%= render partial: 'layouts/portHeader' %>
    <%= yield %>
    <%= render partial: 'layouts/portFooter' %>
  </body>
</html>

app/views/posts/_post_showcase.html.erb
<ul class="blogger">
  <% @posts.each do |post| %>
  <li class="blog_post panel panel-default">
    <div class="panel-heading">
      <small class='pull-right'>
        <%= time_tag(post.created_at) %>
      </small>
      <h2 class="panel-heading">
        <%= link_to "#{post.title}", post_path(post.id) %>
      </h2>
    </div>
    <div class="panel-body">
      <%= render partial: "#{post.body}" %>
    </div>
  </li>
  <% end %>
</ul>

app/views/posts/post_folder/_chrome_extensions.html.erb
<h3 class="postHTop">Chrome Extensions</h3>
<div>
  I recently was given the task by a client to build a Chrome Extension despite my utter lack of experience with it, yet it turned out to be much easier than I expected! In fact once you get the hang of it, devloping Chrome extensions can be quite easy and fun! The developer dashboard is simple to use, costs only $5 to register and has plenty of documentation to get you started.
</div>
<br />
<div>
  <h4>What I Was Asked to Build</h4>
  <div class="indented">
    <p>So the app that was requested by the client was essentially a container for education coursework so that the user could easily toggle between the course and the lesson work which took place on an outside site. Complete with routing, navigtation, authentication and asynchronous data requests the project grew pretty quickly from a simple app to something quite complex. But with some vanilla JS, a bit of jQuery and some time (along with a Django based API that I built) I was able to put it together. It's a privately hosted app only available internally to users of the main application but it was a great learning experience and very rewarding.</p>
  </div>
</div>
<div>
  <h4>What I Decided to Build</h4>
  <div class="indented">
    <p>
      During my experimentation with Chrome extensions and the power that they can wield I ran across a curious bit of an API that I found intriguing... (see <a href="https://developer.chrome.com/extensions/webRequest">here</a>) With this API I could modify, block or just view a variety of aspects related to a web request. I'm talking changes to the header, the body, plenty of things. This could be pretty powerful! So for starters I looked into modifying headers as I had run into issues in development before mocking headers. And in researching this I built a chrome extension that removes x-frame denial headers from a web request essentially enabling iframes wherever you want! Pretty cool indeed.... Check out my extension <a href="https://chrome.google.com/webstore/detail/iframe-freedom/miepmaeldfjckcpkgobkjodogihlgddo">here</a> and please support by shopping though my <a href="https://www.amazon.com/?tag=swentling-20&linkCode=ur1">Amazon</a> link present in the extension popup.
    </p>
  </div>
</div>

app/views/posts/post_folder/_edit_a_dmg.html.erb
<div>
  <p>So I said that I was going to write some posts and here it goes. I recently ran across a situation working on a project where I had an existing <b>DMG</b> file that I needed to change. But... it was read only! And that's to be expected honestly. A full program itself would be expected to be read only and that's what I was dealing with here. We had a full fledged internet browser but needed quick iterations of it created with minor changes for testing purposes. What to do?!</p>
  <p>There answer ultimately proved way easier than I would have ever expected. It turns out that you can change a read only DMG file (while leaving an original untouched) by using the hdiutil functionality on a Mac and all in 4 easy steps.</p>
</div>
<div>
  <ol>
    <li>Open the DMG file and attach it with the command: hdiutil attach -owners on /path/to/your.dmg -shadow</li>
    <li>Make your edits, add files, remove files etc.</li>
    <li>Eject the currently mounted disk (now edited).</li>
    <li>Convert your shadow file to a new cloned DMG using command: hdiutil convert -format UDZO -o /path/to/new.dmg /path/to/your.dmg -shadow</li>
  </ol>
</div>
<div>
  <p>Credit for this very much goes to this blog post found <%= link_to "here", "https://myjeeva.com/best-possible-way-edit-read-only-dmg.html" %></p>
</div>

app/views/posts/post_folder/_find_by_sql.html.erb
<h3 class="postHTop">Find By SQL</h3>
<div>
  This is a story about when I was confronted by a bloated, neglected and worn out Rails 2 application that somehow was limping along without any updates for 2 years and tasked with taking it and beginning to iterate on it. Spoiler alert, it was and is a nightmare to develop on. I truly feel for the early pioneers of Rails (let alone other any other early pioneers of web development), as this was a difficult task.
</div>
<br />
<div>
  <h4>What does this have to do with SQL?</h4>
  <div class="indented">
    Well, it really is less to do with SQL and more to do with ActiveRecord and the wonderous methods that it provides for accessing the database. Methods that I took for granted and was used to using but weren't available in Rails 2. Due to the fact that the application was very brittle, the idea of updating ActiveRecord or even the Rails version was out of the question. I was stuck and had to work with this system at least for now. So when I have a complicated query and don't have methods like join, includes, where or select available what should I do? And that's where find_by_sql came into play.
  </div>
  <h4>Find By SQL</h4>
  <div class="indented">
    It's not pretty, definitely not elegant but it got the job done. There may be a better way to do this, but with budgetary and time contstraints involved as this was a paid project and Rails 2 being deprecated it didn't make sense to dig into it any further when a working solution was found.
  </div>
  <div class="indented">
    So how does it work? Simply put you will start with a model name such as Post and then call the command <code>.find_by_sql</code> and pass it a string of SQL. It's that easy! I've included a very basic example below but the real implementation included multiple joins, some where clauses, order by etc. but with just a simple example you can see how easy and powerful this can be. Just a side note though that this query was run directly (essentially like a scope) and did not receive any user input which could cause some security issues.
  </div>  
  <div class="indented">    
    <pre>
      <code>
        def foo_finder
          query = "SELECT * from foo WHERE foo.name=bar.name"
          Foo.find_by_sql(query)
        end
      </code>
    </pre>
    <br />
  </div>
</div>

app/views/posts/post_folder/_hello_welcome!.html.erb
<p>Welcome to my newly re-designed portfolio. I decided that my previous Jekyll portfolio hosted by GitHub was just not what I was looking for and to make a change. Here you will find my various academic projects, personal projects and some of the professional work that I'm allowed to share. I'm currently holding two jobs with one as a devloper for <b>Phantom Design</b> based out of Los Angeles and my full-time at State Farm as an insurance adjuster. Check back from time to time for updates, things I find interesting and more posts like this.</p>

app/views/posts/post_folder/_input_icons.html.erb
<h3 class="postHTop">Tired of boring old input boxes?!</h3>
<div>
  Random as always, I'm writing about an interesting topic that I came across while working on professional projects. Although mainly a backend developer I sometimes have to handle the frontend as well and in this case was developing a simple sign up and sign in form but with icons in the input box! Note that all code shown below is similiar to the approaches I used but no code has been used directly.
</div>
<div>
  <h4>Option One: Background Image</h4>
  <div class="indented">
    <p>I found this option to be great and simple to implement but it just wouldn't work the way that I needed it to in this circustance. For this particular case I was required to use Ionic-icons and needed to set a border for the icon which wasn't something I could easily manipulate when setting a background image.
    </p>
    <pre>
      <code>
        HTML.ERB File
        &lt;%= password_field_tag :password, placeholder: "Password", class: "password_form_field"%> 
        
        CSS File
        .password_form_field {
          background: url(images/comment-author.gif) no-repeat scroll 7px 7px;
          padding-left:30px;
        }
      </code>
    </pre>
    <br />
  </div>
</div>
<div>
  <h4>Option Two: Wrap it in a Div</h4>
  <p>As I mentioned before, this was the implementation that I used and was great because it allowed me the extra flexibility to build out the options that my client required. By wrapping the entire input along with the icon in a div I could include any icon, image or text as needed and make the div css match the specifications.</p>
  <div class="indented">    
    <pre>
      <code>
        HTML.ERB File
        &lt;div class="password_form_field center-block">
          &lt;i class="icon ion-key placeholder-icon">&lt;/i>
          &lt;%= password_field_tag :password, placeholder: "Password", class: "input"%> 
        &lt;/div>
        
        CSS File
        .password_form_field {
          padding: 5px 0px 5px 0px;
          border-radius: 5px;
          background-color: white;
          line-height: 38px;
          color: white;
          text-align: left
        }
        .placeholder-icon {
          border-right: 2px black solid;
          vertical-align: middle;
          padding-right: 12px;
          font-size: 2em;
          margin-left: 12px;  
        }
        .input {
          color: grey;
          width: 78%;
        }
      </code>
    </pre>
    <br />
  </div>
</div>

app/views/posts/post_folder/_post_goals.html.erb
<p>So... I've accomplished this fancy new portfolio with plenty of projects but no content! It's awfully hard to think of what to write here it turns out. Therefore I'm beginning to keep a list of topics/ideas which I can write about and updating it as I come across these ideas rather than sit here and try to think of something to write about. It's my goal to post something new and technical each week. I'll keep them short and sweet but informative. By writing it here, I'm putting the goal out there so I keep myself more accountable to it.</p>

app/views/posts/post_folder/_rails_conf_2018.html.erb
<h3 class="postHTop">Rails Conf 2018</h3>
<div>
  I got to go to my second conference! I could essentially reiterate what I wrote in my last post about a conference regarding how amazing the experience was, and although this one was quite different but even more amazing than Ruby Conf. The venue was in Pittsburgh and it was definitely cold but a lot of fun with a surprisingly great culinary scene. The conference though, was much larger than I expected and overall more applicable. Although Ruby Conf was great and had some good talks, much of it centered around where Ruby as a language was going rather than the actual implementation of Ruby whereas Rails Conf had plenty of useful talks for learning about ways to use Ruby (with Rails) and a lot more hands on learning from the workshops which I found really valuable. Here's some of the highlights listed below.
</div>
<br />
<div>
  <h4>What to watch...?</h4>
  <div class="indented">
    <ul>
      <li><a href="https://confreaks.tv/videos/railsconf2018-opening-keynote-fixme">Opening Keynote - DHH</a></li>
      <li><a href="https://confreaks.tv/videos/railsconf2018-keynote-the-future-of-rails-6-scalable-by-default">The Future of Rails 6: Scalable by Default - Eileen Uchitelle</a></li>
      <li><a href="https://confreaks.tv/videos/railsconf2018-re-graphing-the-mental-model-of-the-rails-router">Re-graphing The Mental Model of The Rails Router - Vaidehi Joshi</a></li>
      <li><a href="https://confreaks.tv/videos/railsconf2018-closing-keynote">Closing Keynote - Aaron Patterson</a></li>
    </ul>
  </div>
</div>
<div>
  <h4>What to work on...?</h4>
  <div class="indented">
    <ul>
      <li><a href="https://speakerdeck.com/exaspark/graphql-on-rails">GraphQL on Rails - Evgeny Li</a></li>
      <li><a href="https://www.notion.so/RailsConf-PRPL-on-Rails-470694f92d76434cb996967bb216b689">PRPL on Rails - 
Pearl Latteier & Abraham Williams</a></li>
    </ul>
  </div>
</div>

app/views/posts/post_folder/_react_with_rails.html.erb
<h3 class="postHTop">React on Rails</h3>
<div>
  Up front I want to make it known that I won't be going very far in depth here regarding this topic as there truly is a vast amount to cover but I'm taking the time to write this method/approach down as much to share it but also to document it for myself. Specifically, I'm documenting how to get data from a rails controller directly to a React view. I spent some time recently working on a small project using Rails and React with Webpacker and this was a very handy approach.
</div>
<br />
<div>
  <h4>Step One</h4>
  <div class="indented">
    <p>A little background first, I had Rails code and essentially separate React code but in the same app and we were trying to figure out how to connect them together and get data from the backend to the frontend. Turning off Turbolinks was essential to help with links but most importantly we had to change the way the app was handling page requests as this app needed to be more than a single page. So I actually turned off the React Router we had setup and let Rails handle that with each page serving up a new instance of React. The HTML page would get served by rails and simply initialize that React instance as seen below.
    </p>
    <pre>
      <code>
        HTML.ERB File
        &lt;%=  javascript_pack_tag 'Blog' %> 
      </code>
    </pre>
    <br />
  </div>
</div>
<div>
  <h4>Step Two</h4>
  <p>From there I still needed to get the backend data to the frontend. I had the data initialized in an instance variable by the Rails controller and available since the Rails router had directed me to that action but still couldn't get it to the React instance. That's when I found this <%= link_to "solution", "https://hackernoon.com/how-to-get-your-rails-data-into-your-react-component-with-webpacker-647dc63706c9" %> which allowed me to do just what I needed. By placing a hidden div on the HTML page served up by the rails action before the javascript I could effectively pass the data from the controller to the React part of the app as JSON and grab it directly from the DOM.</p>
  <div class="indented">    
    <pre>
      <code>
        HTML.ERB File
        &lt%= content_tag :div,
         id: "blog_data",
         data: @blog.to_json do %>
        &lt% end %>
        &lt;%=  javascript_pack_tag 'Blog' %> 
      </code>
    </pre>
    <br />
  </div>
</div>
<div>
  <h4>Step Three</h4>
  <p>The final step was just to now handle this data properly within the React part of the app and that simply consisted of setting some constants within the JSX file and grabbing that data directly from the DOM to be used as needed.</p>
  <div class="indented">    
    <pre>
      <code>
        JSX File
        const node = document.getElementById('blog_data')
        const blog = JSON.parse(node.getAttribute('data'))
      </code>
    </pre>
    <br />
  </div>
</div>

app/views/posts/post_folder/_ruby_conf_2017.html.erb
<h3 class="postHTop">Ruby Conf 2017</h3>
<div>
  I got to go to my first conference! It was amazing and no BS, it was life changing. The venue was New Orleans and the conference was Ruby Conf 2017. I got to see Matz and Sandi Metz, watch some amazing talks and generally eat, breath and live code for a few solid days. Most of the talks were great, I went with a group from my work (Procore Technologies) and I learned a lot. On a human note, New  Orleans is a blast and has amazing music. Now I'm not going to go into detail regarding everything I learned but I will list some of the best talks I saw. This is as much a blog post as me cataloguing the videos to reference later as I particularly enjoyed these.
</div>
<br />
<div>
  <h4>What to watch...?</h4>
  <div class="indented">
    <ul>
      <li><a href="http://confreaks.tv/videos/rubyconf2017-git-driven-refactoring">Git Driven Refactoring - Ashley Ellis Pierce</a></li>
      <li><a href="http://confreaks.tv/videos/rubyconf2017-keynote-growing-old">Growing Old - Chad Fowler</a></li>
      <li><a href="http://confreaks.tv/videos/rubyconf2017-keynote-the-impermanence-of-software">The Impermanence of Software - Andy Croll</a></li>
      <li><a href="http://confreaks.tv/videos/rubyconf2017-that-time-i-used-ruby-to-crack-my-reddit-password">That time I used Ruby to crack my Reddit password - Haseeb Qureshi</a></li>
      <li><a href="http://confreaks.tv/videos/rubyconf2017-keynote-you-re-insufficiently-persuasive">You're Insufficiently Persuasive - Sandi Metz</a></li>
    </ul>
  </div>
</div>

app/views/posts/post_folder/_sidekiq_cron_fun.html.erb
<h3 class="postHTop">Fun with Sidekiq Cron!</h3>
<div>
  Cron jobs can be very useful but configuring a cron tab isn't the most dev-friendly experience. Beyond that, it isn't necessarily something that any dev in any environment can implement due to access restrictions. Now a side note here is that there are valid gems to do this kind of thing but in the circustance that I was operating under I didn't want to add any new libraries. So this is where Sidekiq Enterprise comes into play. We already were using Sidekiq but hadn't explored any of its features beyond the most basic implementation.
</div>
<br />
<div>
  <h4>How does it work?</h4>
  <div class="indented">
    It's actually pretty straight forwards, it just takes an update the the Sidekiq initializer file and creation of your worker class. Although I glossed over it earlier, it's important to note that this will only work for Sidekiq Enterprise and not the base Sidekiq implementation. In order to setup the initializer properly you'll just need to add the code listed below (taken from the docs <a href="https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs">here</a>) and swap our your worker class for the 2nd position in the register method.
  </div>
  <div class="indented">    
    <pre>
      <code>
        Sidekiq.configure_server do |config|
          config.periodic do |mgr|
            # see any crontab reference for the first argument
            # e.g. http://www.adminschoice.com/crontab-quick-reference
            mgr.register('0 * * * *', SomeHourlyWorkerClass)
            mgr.register('* * * * *', SomeWorkerClass, retry: 2, queue: 'foo')
            mgr.register(cron_expression, worker_class, job_options={})
          end
        end
      </code>
    </pre>
    <br />
  </div>
</div>

app/views/posts/post_folder/_updates_updates!.html.erb
<p>Well even though this may all look very much the same as it has since it's essentially been up online there have been a number of changes lately. You can feel free to check out some of the various changes over at the GitHub repository for this <%= link_to "Here", "https://github.com/swentling87/swentling.com" %>. Careful analysis will show that I've rethought the way that I handle images and their association to projects as well as some improvements on linking throughout the site for better navigation. But the big deal is that you'll find that I've added some shots from professional projects. No code unfortunately but that's the way it goes... Browse through the projects pages and check them out!</p>

app/views/posts/show.html.erb
<section class="container postShow">
  <h1 class="postHeader">
    <%= @post.title.capitalize %>
  </h1>
  <div class="row postRow">
    <div class="col-md-12 col-xs-12 postBody">
      <small>
        <%= time_tag(@post.created_at) %>
      </small><br /><br />
      <%= render partial: "#{@post.body}" %>
    </div>
  </div>
</section>

app/views/projects/_project_template.html.erb
<h3 class="projectBodyHeader">Explanation</h3>
<div class="projectBodyDescription"><%= "#{@project.body}" %></div>
<h3 class="projectBodyHeader">Links</h3>
<h3 class="projectSubHeader"><%= link_to "GitHub", @project.git %></h3>
<h3 class="projectSubHeader"><%= link_to "URL", @project.web %></h3>

app/views/projects/index.html.erb
<section class="container projectIndex">
  <h1 class="projectHeader">My Projects</h1>
  <div class="row projectIndexRow">
    <div class="col-md-12 col-xs-12">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#all" aria-controls="all" role="tab" data-toggle="tab">All</a></li>
        <li role="presentation"><a href="#professional" aria-controls="professional" role="tab" data-toggle="tab">Professional</a></li>
        <li role="presentation"><a href="#personal" aria-controls="personal" role="tab" data-toggle="tab">Personal</a></li>
        <li role="presentation"><a href="#educational" aria-controls="educational" role="tab" data-toggle="tab">Educational</a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="all">
          <% @projects.each do |project| %>
            <div class="thumbWrapper">
              <%= link_to project_path(project.id) do %>
                <div class="thumbnail" style="background-image: url(<%= asset_path "#{project.main_img}.png" %>);">
                </div>
                <h1 class="thumbHeader invisible"><%= link_to "#{project.name.capitalize}", project_path(project.id) %></h1>
              <% end %>
            </div>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane" id="professional">
          <% @pro_projects.each do |project| %>
            <div class="thumbWrapper">
              <%= link_to project_path(project.id) do %>
                <div class="thumbnail" style="background-image: url(<%= asset_path "#{project.main_img}.png" %>);">
                </div>
                <h1 class="thumbHeader invisible"><%= link_to "#{project.name.capitalize}", project_path(project.id) %></h1>
              <% end %>
            </div>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane" id="personal">
          <% @personal_projects.each do |project| %>
            <div class="thumbWrapper">
              <%= link_to project_path(project.id) do %>
                <div class="thumbnail" style="background-image: url(<%= asset_path "#{project.main_img}.png" %>);">
                </div>
                <h1 class="thumbHeader invisible"><%= link_to "#{project.name.capitalize}", project_path(project.id) %></h1>
              <% end %>
            </div>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane" id="educational">
          <% @edu_projects.each do |project| %>
            <div class="thumbWrapper">
              <%= link_to project_path(project.id) do %>
                <div class="thumbnail" style="background-image: url(<%= asset_path "#{project.main_img}.png" %>);">
                </div>
                <h1 class="thumbHeader invisible"><%= link_to "#{project.name.capitalize}", project_path(project.id) %></h1>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/project_folder/_weteachecom.html.erb
<h3 class="projectBodyHeader">Explanation</h3>
<div class="projectBodyDescription">
WeTeachE-com is a Django based e-learning application built to teach e-commerce which I built under contract for Origin Analytics. It consists of a full fledged CRM, sales funnel and various periphery pages.
</div>
<h3 class="projectBodyHeader">Links</h3>
<h3 class="projectSubHeader"><%= link_to "URL", "http://weteachecom.com" %></h3>

app/views/welcome/_showcase.html.erb
<div id="project-showcase" class="carousel slide center-block" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#project-showcase" data-slide-to="0" class="active"></li>
    <li data-target="#project-showcase" data-slide-to="1"></li>
    <li data-target="#project-showcase" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= link_to image_tag("blocitoff-react.png"), project_path(find_project_id_by_img("blocitoff")) %>
    </div>
    <div class="item">
      <%= link_to image_tag("vid_chat.png"), project_path(find_project_id_by_img("vid_chat")) %>
    </div>
    <div class="item">
      <%= link_to image_tag("store.png"), project_path(find_project_id_by_img("store")) %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#project-showcase" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#project-showcase" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>